var iconArray = ["format_clear",
    "format_align_justify",
    "format_line_spacing",
    "toggle_on", "toggle_off",
    "star_outline", "star_half",
    "star_border", "star",
    "radio_button_unchecked",
    "radio_button_checked",
    "indeterminate_check_box",
    "check_box_outline_blank",
    "check_box", "whatshot",
    "thumb_up_alt",
    "thumb_down_alt",
    "sports_volleyball",
    "sports_tennis",
    "sports_soccer", "sports_rugby",
    "sports_motorsports",
    "sports_mma", "sports_kabaddi",
    "sports_hockey",
    "sports_handball",
    "sports_golf",
    "sports_football",
    "sports_esports",
    "sports_cricket",
    "sports_basketball",
    "sports_baseball", "sports",
    "single_bed", "sick", "share",
    "sentiment_very_satisfied",
    "sentiment_very_dissatisfied",
    "sentiment_satisfied",
    "sentiment_neutral",
    "sentiment_dissatisfied",
    "self_improvement", "science",
    "school", "sanitizer",
    "reduce_capacity", "public_off",
    "public", "psychology",
    "precision_manufacturing",
    "poll", "plus_one",
    "person_remove_alt_1",
    "person_remove",
    "person_outline",
    "person_add_alt_1",
    "person_add", "person",
    "people_outline", "people_alt",
    "people", "party_mode", "pages",
    "outdoor_grill",
    "notifications_paused",
    "notifications_off",
    "notifications_none",
    "notifications_active",
    "notifications", "no_luggage",
    "nights_stay", "mood_bad",
    "mood", "military_tech",
    "masks", "luggage",
    "location_city", "king_bed",
    "history_edu", "groups",
    "group_add", "group",
    "follow_the_signs", "fireplace",
    "facebook", "engineering",
    "emoji_transportation",
    "emoji_symbols", "emoji_people",
    "emoji_objects", "emoji_nature",
    "emoji_food_beverage",
    "emoji_flags", "emoji_events",
    "emoji_emotions", "elderly",
    "domain", "deck", "coronavirus",
    "construction",
    "connect_without_contact",
    "clean_hands", "cake",
    "architecture", "6_ft_apart",
    "wheelchair_pickup",
    "water_damage", "wash",
    "umbrella", "tty", "tapas",
    "stroller", "storefront",
    "stairs", "sports_bar", "spa",
    "soap", "smoking_rooms",
    "smoke_free", "rv_hookup",
    "room_service",
    "room_preferences", "roofing",
    "rice_bowl", "pool",
    "no_stroller", "no_photography",
    "no_meeting_room", "no_food",
    "no_flash", "no_drinks",
    "no_cell", "no_backpack",
    "night_shelter", "microwave",
    "meeting_room", "kitchen",
    "house_siding", "house",
    "hot_tub", "grass",
    "golf_course", "free_breakfast",
    "foundation", "food_bank",
    "fitness_center",
    "fire_extinguisher", "fence",
    "family_restroom",
    "escalator_warning",
    "escalator", "elevator", "dry",
    "do_not_touch", "do_not_step",
    "countertops", "corporate_fare",
    "child_friendly", "child_care",
    "checkroom", "charging_station",
    "casino", "carpenter",
    "business_center", "bento",
    "beach_access", "bathtub",
    "backpack",
    "baby_changing_station",
    "apartment", "all_inclusive",
    "airport_shuttle", "ac_unit",
    "wifi_off", "wifi", "wc",
    "vpn_lock", "voice_chat",
    "vibration", "tv_off",
    "time_to_leave", "tap_and_play",
    "system_update", "sync_problem",
    "sync_disabled", "sync",
    "support_agent", "sms_failed",
    "sms", "sd_card_alert",
    "sd_card", "priority_high",
    "power_off", "power",
    "phone_paused", "phone_missed",
    "phone_locked", "phone_in_talk",
    "phone_forwarded",
    "phone_callback",
    "phone_bluetooth_speaker",
    "personal_video",
    "ondemand_video",
    "no_encryption_gmailerrorred",
    "no_encryption",
    "network_locked",
    "network_check", "more", "mms",
    "live_tv", "folder_special",
    "event_note", "event_busy",
    "event_available",
    "enhanced_encryption",
    "drive_eta", "do_disturb_on",
    "do_disturb_off", "do_disturb",
    "do_disturb_alt", "disc_full",
    "bluetooth_audio",
    "confirmation_number",
    "directions_off",
    "airline_seat_recline_normal",
    "menu",
    "airline_seat_legroom_reduced",
    "menu_open",
    "airline_seat_recline_extra",
    "more_horiz",
    "airline_seat_legroom_normal",
    "airline_seat_legroom_extra",
    "airline_seat_individual_suite",
    "airline_seat_flat_angled",
    "airline_seat_flat", "adb",
    "account_tree", "west",
    "unfold_more", "unfold_less",
    "switch_right", "switch_left",
    "subdirectory_arrow_right",
    "subdirectory_arrow_left",
    "south_west", "south_east",
    "south", "refresh", "payments",
    "north_west", "north_east",
    "north", "more_vert",
    "legend_toggle", "last_page",
    "home_work", "fullscreen_exit",
    "fullscreen", "first_page",
    "expand_more", "expand_less",
    "east", "double_arrow", "close",
    "chevron_right", "chevron_left",
    "check", "cancel", "campaign",
    "arrow_upward", "arrow_right",
    "arrow_left",
    "arrow_forward_ios",
    "arrow_forward",
    "arrow_drop_up",
    "arrow_drop_down_circle",
    "arrow_drop_down",
    "arrow_downward",
    "arrow_back_ios", "arrow_back",
    "apps", "app_settings_alt",
    "zoom_out_map",
    "wrong_location", "wine_bar",
    "two_wheeler", "trip_origin",
    "transit_enterexit",
    "transfer_within_a_station",
    "tram", "train", "traffic",
    "terrain", "subway",
    "streetview",
    "store_mall_directory",
    "set_meal", "satellite",
    "run_circle", "restaurant_menu",
    "restaurant", "rate_review",
    "plumbing", "place", "pin_drop",
    "pest_control_rodent",
    "pest_control",
    "person_pin_circle",
    "person_pin", "pedal_bike",
    "not_listed_location",
    "no_transfer", "no_meals",
    "near_me_disabled", "near_me",
    "navigation", "my_location",
    "museum", "multiple_stop",
    "moped", "money",
    "miscellaneous_services",
    "menu_book", "medical_services",
    "maps_ugc", "map", "local_taxi",
    "local_shipping", "local_see",
    "local_printshop",
    "local_post_office",
    "local_police", "local_play",
    "local_pizza", "local_phone",
    "local_pharmacy",
    "local_parking", "local_offer",
    "local_movies", "local_mall",
    "local_library",
    "local_laundry_service",
    "local_hotel", "local_hospital",
    "local_grocery_store",
    "local_gas_station",
    "local_florist",
    "local_fire_department",
    "local_drink", "local_dining",
    "local_convenience_store",
    "local_car_wash", "local_cafe",
    "local_bar", "local_atm",
    "local_airport",
    "local_activity",
    "layers_clear", "layers",
    "hvac", "hotel",
    "home_repair_service",
    "handyman", "flight",
    "fastfood", "ev_station",
    "electrical_services",
    "electric_scooter",
    "electric_rickshaw",
    "electric_moped",
    "electric_car", "electric_bike",
    "edit_road", "edit_location",
    "edit_attributes",
    "directions_walk",
    "directions_transit",
    "directions_subway",
    "directions_run",
    "directions_railway",
    "directions_car",
    "directions_bus",
    "directions_boat",
    "directions_bike", "directions",
    "design_services",
    "departure_board",
    "compass_calibration",
    "cleaning_services", "category",
    "bike_scooter", "beenhere",
    "atm", "alt_route",
    "agriculture", "add_road",
    "add_location_alt",
    "add_location", "add_business",
    "360", "wb_sunny",
    "wb_iridescent",
    "wb_incandescent", "wb_cloudy",
    "wb_auto", "vignette",
    "view_compact", "view_comfy",
    "tune", "transform", "tonality",
    "timer_off", "timer_3",
    "timer_10", "timer",
    "timelapse", "texture",
    "tag_faces", "switch_video",
    "switch_camera", "style",
    "straighten", "slideshow",
    "shutter_speed", "rotate_right",
    "rotate_left",
    "rotate_90_degrees_ccw",
    "remove_red_eye",
    "receipt_long", "portrait",
    "picture_as_pdf",
    "photo_size_select_small",
    "photo_size_select_large",
    "photo_size_select_actual",
    "photo_library", "photo_filter",
    "photo_camera", "photo_album",
    "photo", "panorama_wide_angle",
    "panorama_vertical",
    "panorama_horizontal",
    "panorama_fish_eye", "panorama",
    "palette", "navigate_next",
    "navigate_before",
    "nature_people", "nature",
    "music_off", "music_note",
    "movie_filter",
    "movie_creation",
    "motion_photos_paused",
    "motion_photos_pause",
    "motion_photos_on",
    "monochrome_photos", "loupe",
    "looks_two", "looks_one",
    "looks_6", "looks_5", "looks_4",
    "looks_3", "looks",
    "linked_camera", "lens",
    "leak_remove", "leak_add",
    "landscape", "iso",
    "image_search",
    "image_not_supported",
    "image_aspect_ratio", "image",
    "healing", "hdr_weak",
    "hdr_strong", "hdr_on",
    "hdr_off", "grid_on",
    "grid_off", "grain", "gradient",
    "flip_camera_ios",
    "flip_camera_android", "flip",
    "flash_on", "flash_off",
    "flash_auto", "flare",
    "filter_vintage",
    "filter_tilt_shift",
    "filter_none", "filter_hdr",
    "filter_frames", "filter_drama",
    "filter_center_focus",
    "filter_b_and_w",
    "filter_9_plus", "filter_9",
    "filter_8", "filter_7",
    "filter_6", "filter_5",
    "filter_4", "filter_3",
    "filter_2", "filter_1",
    "filter", "exposure_zero",
    "exposure_plus_2",
    "exposure_plus_1",
    "exposure_neg_2",
    "exposure_neg_1", "exposure",
    "euro", "edit", "details",
    "dehaze", "crop_square",
    "crop_rotate", "crop_portrait",
    "crop_original",
    "crop_landscape", "crop_free",
    "crop_din", "crop_7_5",
    "crop_5_4", "crop_3_2",
    "crop_16_9", "crop",
    "control_point_duplicate",
    "control_point", "compare",
    "colorize", "color_lens",
    "collections_bookmark",
    "collections",
    "center_focus_weak",
    "center_focus_strong",
    "camera_roll", "camera_rear",
    "camera_front", "camera_alt",
    "camera", "burst_mode", "brush",
    "broken_image", "brightness_7",
    "brightness_6", "brightness_5",
    "brightness_4", "brightness_3",
    "brightness_2", "brightness_1",
    "blur_on", "blur_off",
    "blur_linear", "blur_circular",
    "bedtime", "audiotrack",
    "assistant_photo", "assistant",
    "adjust", "add_to_photos",
    "add_photo_alternate",
    "add_a_photo", "sensor_window",
    "sensor_door", "watch",
    "videogame_asset", "tv", "toys",
    "tablet_mac", "tablet_android",
    "tablet", "speaker_group",
    "speaker", "smartphone",
    "sim_card", "security",
    "scanner", "router",
    "power_input", "point_of_sale",
    "phonelink_off", "phonelink",
    "phone_iphone", "phone_android",
    "mouse", "memory",
    "laptop_windows", "laptop_mac",
    "laptop_chromebook", "laptop",
    "keyboard_voice",
    "keyboard_tab",
    "keyboard_return",
    "keyboard_hide",
    "keyboard_capslock",
    "keyboard_backspace",
    "keyboard_arrow_up",
    "keyboard_arrow_right",
    "keyboard_arrow_left",
    "keyboard_arrow_down",
    "keyboard", "headset_mic",
    "headset", "gamepad", "dock",
    "devices_other",
    "device_unknown", "device_hub",
    "developer_board",
    "desktop_windows",
    "desktop_mac", "computer",
    "cast_for_education",
    "cast_connected", "cast",
    "browser_not_supported",
    "upload", "topic",
    "text_snippet",
    "snippet_folder", "rule_folder",
    "request_quote",
    "folder_shared", "folder_open",
    "folder", "download_done",
    "download", "create_new_folder",
    "cloud_off", "cloud_queue",
    "cloud_upload",
    "cloud_download", "title",
    "cloud_circle", "wrap_text",
    "cloud_done", "attach_email",
    "cloud", "attachment",
    "text_fields",
    "vertical_align_bottom",
    "vertical_align_top",
    "vertical_align_center",
    "table_rows", "table_chart",
    "superscript", "subscript",
    "strikethrough_s",
    "stacked_line_chart",
    "post_add", "pie_chart_outline",
    "multiline_chart", "space_bar",
    "show_chart", "short_text",
    "score", "scatter_plot",
    "publish", "notes", "pie_chart",
    "money_off_csred", "money_off",
    "insert_drive_file",
    "insert_comment",
    "insert_emoticon",
    "monetization_on",
    "mode_comment", "mode",
    "merge_type", "linear_scale",
    "insert_photo", "insert_link",
    "insert_invitation",
    "insert_chart_outlined",
    "insert_chart",
    "horizontal_rule", "highlight",
    "height", "functions",
    "format_underlined",
    "format_textdirection_r_to_l",
    "format_textdirection_l_to_r",
    "format_strikethrough",
    "format_paint", "format_shapes",
    "format_quote", "format_size",
    "format_list_numbered_rtl",
    "format_list_numbered",
    "format_list_bulleted",
    "format_align_right",
    "format_italic",
    "format_color_reset",
    "format_color_fill",
    "format_color_text",
    "format_indent_increase",
    "format_indent_decrease",
    "border_clear",
    "signal_wifi_1_bar_lock",
    "developer_mode", "drag_handle",
    "format_bold",
    "border_vertical",
    "format_align_left",
    "border_style",
    "format_align_center",
    "border_top", "bubble_chart",
    "network_cell", "border_outer",
    "border_left", "border_right",
    "border_horizontal",
    "border_all", "border_inner",
    "attach_money", "border_color",
    "sd_storage", "border_bottom",
    "attach_file", "bar_chart",
    "signal_cellular_0_bar",
    "settings_system_daydream",
    "add_comment", "wifi_tethering",
    "wifi_lock", "widgets",
    "wallpaper", "usb",
    "thermostat", "storage",
    "signal_wifi_off",
    "signal_wifi_4_bar_lock",
    "signal_wifi_4_bar",
    "signal_wifi_3_bar_lock",
    "signal_wifi_3_bar",
    "signal_wifi_2_bar_lock",
    "signal_wifi_2_bar",
    "check_circle",
    "signal_wifi_1_bar",
    "signal_wifi_0_bar",
    "signal_cellular_off",
    "signal_cellular_null",
    "signal_cellular_no_sim",
    "signal_cellular_connected_no_internet_4_bar",
    "signal_cellular_connected_no_internet_3_bar",
    "signal_cellular_connected_no_internet_2_bar",
    "signal_cellular_connected_no_internet_1_bar",
    "signal_cellular_connected_no_internet_0_bar",
    "signal_cellular_alt",
    "signal_cellular_4_bar",
    "signal_cellular_3_bar",
    "signal_cellular_2_bar",
    "signal_cellular_1_bar",
    "screen_rotation",
    "screen_lock_rotation",
    "screen_lock_portrait",
    "screen_lock_landscape", "nfc",
    "network_wifi",
    "location_disabled",
    "mobile_off", "mobile_friendly",
    "location_searching",
    "dashboard", "bluetooth",
    "bluetooth_disabled",
    "bluetooth_connected",
    "graphic_eq", "gps_off",
    "gps_not_fixed", "gps_fixed",
    "dvr", "devices", "rowing",
    "data_usage",
    "brightness_medium",
    "brightness_low",
    "brightness_high",
    "brightness_auto",
    "bluetooth_searching",
    "battery_full",
    "battery_charging_full",
    "battery_unknown",
    "battery_std",
    "battery_charging_90",
    "battery_charging_80",
    "battery_charging_60",
    "battery_charging_50",
    "battery_charging_30",
    "battery_charging_20",
    "battery_alert", "battery_90",
    "battery_80", "battery_60",
    "battery_50", "battery_30",
    "battery_20",
    "airplanemode_inactive",
    "airplanemode_active",
    "add_to_home_screen",
    "add_alarm", "ad_units",
    "access_time", "access_alarms",
    "access_alarm", "where_to_vote",
    "weekend", "waves", "undo",
    "unarchive", "text_format",
    "square_foot", "sort", "send",
    "select_all", "save_alt",
    "save", "report_off",
    "report_gmailerrorred",
    "report", "reply_all", "reply",
    "remove_circle_outline",
    "remove_circle", "remove",
    "redo", "push_pin", "policy",
    "outlined_flag", "next_week",
    "move_to_inbox", "markunread",
    "mail", "low_priority",
    "link_off", "link", "insights",
    "inbox", "how_to_vote",
    "how_to_reg", "gesture",
    "forward", "font_download",
    "flag", "filter_list",
    "file_copy", "dynamic_feed",
    "drafts", "delete_sweep",
    "create", "content_paste",
    "content_cut", "content_copy",
    "clear", "calculate", "block",
    "biotech", "ballot",
    "backspace", "attribution",
    "archive", "amp_stories",
    "add_circle_outline",
    "add_circle", "add_box", "add",
    "wifi_calling", "vpn_key",
    "voicemail", "unsubscribe",
    "textsms", "swap_calls",
    "stop_screen_share",
    "stay_primary_portrait",
    "stay_primary_landscape",
    "stay_current_portrait",
    "stay_current_landscape",
    "speaker_phone",
    "sentiment_satisfied_alt",
    "screen_share", "rss_feed",
    "ring_volume", "read_more",
    "qr_code_scanner", "qr_code",
    "print_disabled",
    "present_to_all",
    "portable_wifi_off",
    "phonelink_setup",
    "phonelink_ring",
    "phonelink_lock",
    "phonelink_erase",
    "phone_enabled",
    "phone_disabled", "phone",
    "person_search",
    "person_add_disabled",
    "pause_presentation", "no_sim",
    "nat", "more_time",
    "mobile_screen_share",
    "message", "mark_email_unread",
    "mark_email_read",
    "mark_chat_unread",
    "mark_chat_read",
    "mail_outline", "location_on",
    "location_off", "live_help",
    "list_alt", "invert_colors_off",
    "import_export",
    "import_contacts",
    "hourglass_top",
    "hourglass_bottom",
    "forward_to_inbox", "forum",
    "email", "duo",
    "domain_verification",
    "domain_disabled", "dialpad",
    "dialer_sip",
    "desktop_access_disabled",
    "contacts", "contact_phone",
    "contact_mail", "comment",
    "clear_all",
    "chat_bubble_outline",
    "chat_bubble", "chat",
    "cell_wifi",
    "cancel_presentation",
    "call_split", "call_received",
    "call_missed_outgoing",
    "call_missed", "call_merge",
    "call_made", "call_end", "call",
    "business", "alternate_email",
    "add_ic_call", "web_asset",
    "web", "volume_up",
    "volume_off", "volume_mute",
    "volume_down", "videocam_off",
    "videocam", "video_settings",
    "video_library", "video_label",
    "video_call", "surround_sound",
    "subtitles", "subscriptions",
    "stop_circle", "stop", "speed",
    "sort_by_alpha", "snooze",
    "slow_motion_video",
    "skip_previous", "skip_next",
    "shuffle", "replay_5",
    "replay_30", "replay_10",
    "replay", "repeat_one",
    "repeat", "remove_from_queue",
    "recent_actors", "radio",
    "queue_play_next",
    "queue_music", "queue",
    "playlist_play",
    "playlist_add_check",
    "playlist_add",
    "play_circle_outline",
    "play_circle_filled",
    "play_arrow",
    "pause_circle_outline",
    "pause_circle_filled", "pause",
    "note", "not_interested",
    "new_releases", "music_video",
    "movie", "missed_video_call",
    "mic_off", "mic_none", "mic",
    "loop", "library_music",
    "library_books",
    "library_add_check",
    "library_add", "high_quality",
    "hearing_disabled", "hearing",
    "hd", "games", "forward_5",
    "forward_30", "forward_10",
    "fiber_smart_record",
    "fiber_pin", "fiber_new",
    "fiber_manual_record",
    "fiber_dvr", "featured_video",
    "featured_play_list",
    "fast_rewind", "fast_forward",
    "explicit", "equalizer",
    "control_camera",
    "closed_caption_disabled",
    "closed_caption",
    "call_to_action",
    "branding_watermark",
    "av_timer", "art_track",
    "album", "airplay",
    "add_to_queue", "5g", "4k",
    "warning_amber", "warning",
    "notification_important",
    "error_outline", "error",
    "auto_delete", "add_alert",
    "zoom_out", "zoom_in",
    "youtube_searched_for",
    "wysiwyg", "work_outline",
    "work_off", "work",
    "wifi_protected_setup",
    "watch_later", "voice_over_off",
    "visibility_off", "visibility",
    "view_week", "view_stream",
    "view_sidebar", "view_quilt",
    "view_module", "view_list",
    "view_headline", "view_day",
    "view_column", "view_carousel",
    "view_array", "view_agenda",
    "vertical_split",
    "verified_user", "verified",
    "upgrade", "update",
    "unpublished", "turned_in_not",
    "turned_in", "trending_up",
    "trending_flat",
    "trending_down", "translate",
    "track_changes", "tour",
    "touch_app", "toll", "today",
    "toc", "timeline",
    "thumbs_up_down", "thumb_up",
    "thumb_down", "theaters",
    "text_rotation_none",
    "text_rotation_down",
    "text_rotation_angleup",
    "text_rotation_angledown",
    "text_rotate_vertical",
    "text_rotate_up", "table_view",
    "tab_unselected", "tab",
    "system_update_alt", "sync_alt",
    "swap_vertical_circle",
    "swap_vert",
    "swap_horizontal_circle",
    "swap_horiz", "support",
    "supervisor_account",
    "supervised_user_circle",
    "subtitles_off", "subject",
    "stars", "store",
    "sticky_note_2", "star_rate",
    "spellcheck",
    "speaker_notes_off",
    "speaker_notes", "source",
    "smart_button", "shopping_cart",
    "shopping_basket",
    "shopping_bag", "shop_two",
    "shop", "settings_voice",
    "settings_remote",
    "settings_power",
    "settings_phone",
    "settings_overscan",
    "settings_input_svideo",
    "settings_input_hdmi",
    "settings_input_composite",
    "settings_input_component",
    "settings_input_antenna",
    "settings_ethernet",
    "settings_cell",
    "settings_brightness",
    "settings_bluetooth",
    "settings_backup_restore",
    "settings_applications",
    "settings", "search_off",
    "search", "schedule", "rule",
    "credit_card", "rounded_corner",
    "room", "restore_page",
    "restore_from_trash", "restore",
    "request_page",
    "report_problem", "reorder",
    "remove_shopping_cart",
    "redeem", "record_voice_over",
    "receipt", "quickreply",
    "question_answer",
    "query_builder",
    "published_with_changes",
    "privacy_tip", "print",
    "preview", "pregnant_woman",
    "power_settings_new", "polymer",
    "play_for_work", "plagiarism",
    "picture_in_picture_alt",
    "picture_in_picture", "pets",
    "perm_scan_wifi",
    "perm_phone_msg", "perm_media",
    "perm_identity",
    "perm_device_information",
    "perm_data_setting",
    "perm_contact_calendar",
    "perm_camera_mic",
    "pending_actions", "pending",
    "payment", "pan_tool",
    "pageview", "outlet", "outbond",
    "open_with", "open_in_new",
    "open_in_full",
    "open_in_browser", "opacity",
    "online_prediction",
    "offline_pin", "offline_bolt",
    "note_add", "not_started",
    "not_accessible", "next_plan",
    "model_training", "minimize",
    "mediation", "maximize",
    "markunread_mailbox", "loyalty",
    "login", "lock_outline",
    "lock_open", "lock", "list",
    "line_weight", "line_style",
    "lightbulb_outline",
    "leaderboard", "launch",
    "language", "label_outline",
    "label_off",
    "label_important_outline",
    "label_important", "label",
    "invert_colors",
    "integration_instructions",
    "input", "info_outline", "info",
    "important_devices", "https",
    "http", "hourglass_full",
    "hourglass_empty",
    "hourglass_disabled",
    "horizontal_split", "home",
    "history_toggle_off", "history",
    "highlight_off",
    "highlight_alt", "help_outline",
    "help_center", "help",
    "group_work", "grading",
    "grade", "gif", "get_app",
    "gavel", "g_translate",
    "flip_to_front", "flip_to_back",
    "flight_takeoff", "flight_land",
    "flaky", "fingerprint",
    "find_replace", "find_in_page",
    "filter_alt", "feedback",
    "favorite_border", "favorite",
    "fact_check", "face_unlock",
    "face", "extension",
    "explore_off", "explore",
    "exit_to_app", "event_seat",
    "event", "euro_symbol", "eject",
    "eco", "dynamic_form",
    "drag_indicator", "donut_small",
    "donut_large", "done_outline",
    "done_all", "done", "dns",
    "disabled_by_default",
    "description", "delete_outline",
    "delete_forever", "delete",
    "date_range", "arrow_right_alt",
    "camera_enhance", "copyright",
    "contactless",
    "contact_support",
    "contact_page",
    "compare_arrows", "commute",
    "comment_bank", "code",
    "close_fullscreen", "class",
    "chrome_reader_mode",
    "check_circle_outline",
    "calendar_view_day",
    "change_history", "card_travel",
    "card_membership",
    "card_giftcard",
    "cancel_schedule_send",
    "announcement", "bookmark",
    "calendar_today", "cached",
    "build_circle", "build",
    "bug_report", "bookmarks",
    "bookmark_border", "article",
    "book_online", "book",
    "batch_prediction",
    "backup_table", "backup",
    "autorenew",
    "assignment_turned_in",
    "assignment_returned",
    "assignment_return",
    "assignment_late",
    "assignment_ind", "assignment",
    "assessment", "aspect_ratio",
    "all_out", "arrow_circle_up",
    "arrow_circle_down",
    "app_blocking", "api",
    "android", "anchor",
    "analytics", "all_inbox",
    "alarm_on", "alarm_off",
    "alarm_add", "alarm",
    "admin_panel_settings",
    "addchart", "add_task",
    "add_shopping_cart",
    "account_circle", "account_box",
    "account_balance_wallet",
    "account_balance",
    "accessible_forward",
    "accessible",
    "accessibility_new",
    "accessibility", "3d_rotation",
    "star_purple500",
    "star_border_purple500",
    "lightbulb", "switch_account",
    "remove_moderator", "recommend",
    "person_add_alt", "ios_share",
    "add_moderator",
    "sim_card_alert",
    "imagesearch_roller",
    "do_not_disturb_on",
    "do_not_disturb_off",
    "do_not_disturb_alt",
    "do_not_disturb", "add_call",
    "waterfall_chart",
    "pivot_table_chart",
    "offline_share",
    "assistant_navigation",
    "assistant_direction",
    "volunteer_activism",
    "theater_comedy", "taxi_alert",
    "takeout_dining",
    "ramen_dining", "railway_alert",
    "park", "no_meals_ouline",
    "nightlife", "lunch_dining",
    "location_pin", "liquor",
    "icecream", "hardware", "hail",
    "festival", "dry_cleaning",
    "dinner_dining",
    "delivery_dining",
    "celebration", "car_repair",
    "car_rental", "bus_alert",
    "brunch_dining",
    "breakfast_dining",
    "bakery_dining", "badge",
    "attractions", "wb_twighlight",
    "wb_shade",
    "photo_camera_front",
    "photo_camera_back",
    "panorama_vertical_select",
    "panorama_wide_angle_select",
    "panorama_photosphere_select",
    "panorama_photosphere",
    "panorama_horizontal_select",
    "7k", "mp", "motion_photos_off",
    "mic_external_on",
    "mic_external_off",
    "hdr_enhanced_select",
    "face_retouching_natural",
    "dirty_lens", "circle", "cases",
    "auto_stories", "auto_fix_off",
    "auto_fix_normal",
    "auto_fix_high",
    "auto_awesome_motion",
    "auto_awesome_mosaic",
    "auto_awesome", "animation",
    "9mp", "8mp", "7mp", "6mp",
    "5mp", "4mp", "3mp", "2mp",
    "24mp", "23mp", "22mp", "21mp",
    "20mp", "19mp", "18mp", "17mp",
    "16mp", "15mp", "14mp", "13mp",
    "12mp", "11mp", "10mp",
    "monitor", "headset_off",
    "connected_tv",
    "workspaces_outline",
    "workspaces_filled",
    "upload_file", "grid_view",
    "file_upload",
    "file_download_done",
    "file_download",
    "drive_folder_upload",
    "drive_file_rename_outline",
    "drive_file_move_outline",
    "drive_file_move", "approval",
    "pie_chart_outlined", "padding",
    "mode_edit", "margin",
    "add_chart", "send_to_mobile",
    "screen_search_desktop",
    "reset_tv", "device_thermostat",
    "5k_plus", "tag", "stream",
    "stacked_bar_chart", "shield",
    "inventory", "bolt",
    "block_flipped", "add_link",
    "rtt", "app_registration",
    "shuffle_on", "sd",
    "replay_circle_filled",
    "repeat_one_on", "repeat_on",
    "play_disabled",
    "closed_caption_off", "9k_plus",
    "9k", "8k_plus", "8k",
    "7k_plus", "1k_plus", "6k_plus",
    "6k", "outbox", "5k", "4k_plus",
    "3k_plus", "3k", "2k_plus",
    "2k", "1k", "10k", "view_in_ar",
    "thumb_up_off_alt",
    "thumb_down_off_alt", "swipe",
    "send_and_archive", "segment",
    "schedule_send", "saved_search",
    "remove_done", "outgoing_mail",
    "nightlight_round",
    "mark_as_unread", "logout",
    "lock_clock", "home_filled",
    "fit_screen", "filter_list_alt",
    "file_present", "expand",
    "edit_off",
    "dashboard_customize",
    "dangerous", "compress",
    "circle_notifications",
    "add_to_drive"
];